### ISSUE TITLE
magic square feedback

### ISSUE THREAD

**Issue by RadoRado** [plamer/Programming0#1]
Наред по кода:

Тази if проверка е напълно излишна и грешна (няма ands):

```python
if row_sum(square) == diagonal1(square) == diagonal2(square) == lines(square):
		return True

	else:
		return False
```

Можеш да направиш директно:

```
return row_sum(square) == diagonal1(square) and row_sum(square) == diagonal2(square) and row_sum(square) == lines(square):
```

Така е по-добре и по-вярно.

Не прави вложени функции. изкарам `sumrow` извън `row_sum` !

Също така, ако искаш да намериш сумата на нещо в списък си има вградена функция `sum` в Python.

Другите неща изглеждат добре :)

**Comment by plamer** [comment]
Окей, благодаря много, мисля, че пооправих нещата :)

**Comment by RadoRado** [comment]
С кой commit е това?

**Comment by plamer** [comment]
https://github.com/plamer/Programming0/commit/deab88f58f94a135fe9b3d101ea22475275beb8a

**Comment by RadoRado** [comment]
Супер, така е по-добре :beers:
